[env:esp32devkitc]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Wall
    -Wextra
    -Wno-unused-parameter
    -Wno-sign-compare
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
    https://github.com/me-no-dev/AsyncTCP.git#master
    https://github.com/me-no-dev/ESPAsyncWebServer.git#master
    bblanchon/ArduinoJson@^7.0.4
    lovyan03/LovyanGFX@^1.1.8

[env:lilygo_tdisplay_v1]
platform = espressif32
board = ttgo-t-display
framework = arduino
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Wall
    -Wextra
    -Wno-unused-parameter
    -Wno-sign-compare
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
    https://github.com/me-no-dev/AsyncTCP.git#master
    https://github.com/me-no-dev/ESPAsyncWebServer.git#master
    bblanchon/ArduinoJson@^7.0.4
    lovyan03/LovyanGFX@^1.1.8

[env:esp32_2432s028]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -Wall
    -Wextra
    -Wno-unused-parameter
    -Wno-sign-compare
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
    me-no-dev/AsyncTCP@^1.1.5
    me-no-dev/ESPAsyncWebServer@^3.2.0
    bblanchon/ArduinoJson@^7.0.4
    lovyan03/LovyanGFX@^1.1.8

[platformio]
src_dir = src
lib_dir = lib
test_dir = test
boards_dir = boards
include_dir = include