#!/usr/bin/env bash
# Download Espressif standalone esptool into installer assets (T027).
# Usage: ./scripts/bundle-esptool.sh [macos|linux|windows|all]
# Compatible with macOS system Bash 3.2 (no associative arrays).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VER="${ESPTOOL_VERSION:-v5.3.0}"
BASE="https://github.com/espressif/esptool/releases/download/${VER}"
DEST="$ROOT/apps/esp32-desktop-installer/assets/tools"
CHECKSUMS="$ROOT/apps/esp32-desktop-installer/packaging/ESPTOOL_CHECKSUMS.txt"

target="${1:-}"
if [ -z "$target" ]; then
  case "$(uname -s)" in
    Darwin) target=macos ;;
    Linux) target=linux ;;
    MINGW*|MSYS*|CYGWIN*) target=windows ;;
    *) echo "Pass macos|linux|windows|all"; exit 1 ;;
  esac
fi

# Archive SHA256 from Espressif VirusTotal notes (release assets).
expected_sha() {
  case "$1" in
    macos-arm64) echo "78369f963f1454ecc1b5516119e43aa5aa5cc1afeaca467458cbbeef02675dd4" ;;
    macos-amd64) echo "ea33d15db3cc1f7aec1e6af0ed327ec13c82f139f442a100eca76d5b29094be9" ;;
    linux-amd64) echo "46ca7b52c309790bc4d140990680f6088e8cad40b230fda6999661efc24845b6" ;;
    linux-aarch64) echo "5a03918919f0b94222b639803e97e74d679d0fc3c5092cf27292f8e5a1430794" ;;
    windows-amd64) echo "c86e30586e559f0ae5b41a828f21b4c69a7fc11a194e09391f5a2e31952b2471" ;;
    *) echo "" ;;
  esac
}

sha256_file() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  else sha256sum "$1" | awk '{print $1}'
  fi
}

fetch_one() {
  local os="$1" arch="$2" archive="$3" out_name="$4"
  local url="$BASE/$archive"
  local tmp
  tmp="$(mktemp -d)"
  echo "Downloading $url"
  curl -fsSL -o "$tmp/$archive" "$url"
  local got expect
  got="$(sha256_file "$tmp/$archive")"
  expect="$(expected_sha "${os}-${arch}")"
  if [ -n "$expect" ] && [ "$got" != "$expect" ]; then
    echo "SHA256 mismatch for $archive"
    echo "  expected $expect"
    echo "  got      $got"
    rm -rf "$tmp"
    exit 1
  fi
  mkdir -p "$DEST/$os" "$tmp/out"
  if [[ "$archive" == *.zip ]]; then
    unzip -qo "$tmp/$archive" -d "$tmp/out"
  else
    tar -xzf "$tmp/$archive" -C "$tmp/out"
  fi
  local bin
  bin="$(find "$tmp/out" -type f \( -name esptool -o -name esptool.exe \) | head -1)"
  if [ -z "$bin" ]; then
    echo "esptool binary not found inside $archive"
    rm -rf "$tmp"
    exit 1
  fi
  cp "$bin" "$DEST/$os/$out_name"
  chmod +x "$DEST/$os/$out_name" 2>/dev/null || true
  local bin_sha
  bin_sha="$(sha256_file "$DEST/$os/$out_name")"
  echo "$bin_sha  assets/tools/$os/$out_name" >>"$CHECKSUMS.tmp"
  echo "Installed $DEST/$os/$out_name (sha256=$bin_sha)"
  rm -rf "$tmp"
}

: >"$CHECKSUMS.tmp"
echo "# esptool ${VER} — generated by scripts/bundle-esptool.sh" >>"$CHECKSUMS.tmp"
echo "# Archive SHA256 verified against Espressif release notes before extract." >>"$CHECKSUMS.tmp"

bundle_macos() {
  local arch
  arch="$(uname -m)"
  if [ "$arch" = "arm64" ]; then
    fetch_one macos arm64 "esptool-${VER}-macos-arm64.tar.gz" esptool
  else
    fetch_one macos amd64 "esptool-${VER}-macos-amd64.tar.gz" esptool
  fi
}

bundle_linux() {
  local arch
  arch="$(uname -m)"
  if [ "$arch" = "aarch64" ] || [ "$arch" = "arm64" ]; then
    fetch_one linux aarch64 "esptool-${VER}-linux-aarch64.tar.gz" esptool
  else
    fetch_one linux amd64 "esptool-${VER}-linux-amd64.tar.gz" esptool
  fi
}

bundle_windows() {
  fetch_one windows amd64 "esptool-${VER}-windows-amd64.zip" esptool.exe
}

case "$target" in
  macos) bundle_macos ;;
  linux) bundle_linux ;;
  windows) bundle_windows ;;
  all)
    case "$(uname -s)" in
      Darwin) bundle_macos ;;
      Linux) bundle_linux ;;
      *) bundle_windows ;;
    esac
    echo "Note: 'all' on one host only fetches the current OS. Cross-fetch requires CI."
    ;;
  *) echo "Unknown target $target"; exit 1 ;;
esac

mv "$CHECKSUMS.tmp" "$CHECKSUMS"
echo "Wrote $CHECKSUMS"
